spring:
  datasource:
    url: jdbc:h2:D:/Victor/fiapcervejariabatch;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap

file:
  path: D:\Victor\35SCJ_Spring01\Arquivos\cervejaria-batch-tasklet.zip
  input: classpath:Pessoa.txt